version: "3.5"

services:
  # for VSCode Dev Container
  work:
    build:
      context: "."
      dockerfile: Dockerfile
      target: work-base
    working_dir: "/work/"
    command: [ "sleep", "infinity" ]
    volumes:
      - "./:/work/:delegated"
    environment:
      - SPANNER_EMULATOR_HOST=spanner:9010

  # to test implementation for spanner
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
