version: "3.5"

services:
  test:
    # to test implementation for spanner
    build:
      context: ../
      dockerfile: Dockerfile
      target: work-base
    working_dir: /work
    command: [ "go", "test", "./sqlite/..." ]
    volumes:
      - ../:/work/
    environment:
      - GOTAFACE_TEST_SQLITE_SCHEMA_DB_DIR=/work/sqlite/schema
