// Code generated by cyamli v0.0.11, DO NOT EDIT.
package main

import (
	"fmt"
	"strconv"
	"strings"
)

type Func[Input any] func(subcommand []string, input Input, inputErr error) (err error)

type CLI struct {
	FUNC Func[CLI_Input]
}

func (CLI) DESC_Simple() string {
	return "gaf-postgres-fetch-schema (v0.0.2):\nFetches schema data from a table in a SQLite3 database.\n\nUsage:\n    $ gaf-postgres-fetch-schema [<option>|<argument>]... [-- [<argument>]...]\n\nOptions:\n    -format, -help, -input-txt-tpl, -output\n\nArguments:\n    <data_source> <target_tables>...\n\n"
}
func (CLI) DESC_Detail() string {
	return "gaf-postgres-fetch-schema (v0.0.2):\nFetches schema data from a table in a SQLite3 database.\n\nUsage:\n    $ gaf-postgres-fetch-schema [<option>|<argument>]... [-- [<argument>]...]\n\n\nOptions:\n    -format=<string>  (default=\"json\"):\n        Specifies output format:\n         * json: outputs in JSON format.\n         * txt.tpl: processes template text from stdin in form Go's text/template and outputs result. Available data in the template is described in https://github.com/Jumpaku/gotaface/blob/main/sqlite3/schema/fetch.go#L25\n\n    -help[=<boolean>], -h[=<boolean>]  (default=false):\n        Shows help.\n\n    -input-txt-tpl=<string>  (default=\"\"):\n        Specifies input template file. It can be used with -format=txt.tpl. The stdin is specified in default.\n\n    -output=<string>  (default=\"\"):\n        Specifies output path. The stdout is specified in default.\n\n\nArguments:\n    [0]  <data_source:string>\n        Specifies path to SQLite3 database file.\n\n    [1:] [<target_tables:string>]...\n        Specify target tables to be fetched schemas.\n\n"
}

type CLI_Input struct {
	Opt_Format string

	Opt_Help bool

	Opt_InputTxtTpl string

	Opt_Output string

	Arg_DataSource string

	Arg_TargetTables []string
}

func resolve_CLI_Input(input *CLI_Input, restArgs []string) error {
	*input = CLI_Input{

		Opt_Format: "json",

		Opt_Help: false,

		Opt_InputTxtTpl: "",

		Opt_Output: "",
	}

	var arguments []string
	for idx, arg := range restArgs {
		if arg == "--" {
			arguments = append(arguments, restArgs[idx+1:]...)
			break
		}
		if !strings.HasPrefix(arg, "-") {
			arguments = append(arguments, arg)
			continue
		}
		optName, lit, cut := strings.Cut(arg, "=")
		consumeVariables(optName, lit, cut)

		switch optName {
		default:
			return fmt.Errorf("unknown option %q", optName)

		case "-format":
			if !cut {
				return fmt.Errorf("value is not specified to option %q", optName)

			}
			if err := parseValue(&input.Opt_Format, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		case "-help", "-h":
			if !cut {
				lit = "true"

			}
			if err := parseValue(&input.Opt_Help, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		case "-input-txt-tpl":
			if !cut {
				return fmt.Errorf("value is not specified to option %q", optName)

			}
			if err := parseValue(&input.Opt_InputTxtTpl, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		case "-output":
			if !cut {
				return fmt.Errorf("value is not specified to option %q", optName)

			}
			if err := parseValue(&input.Opt_Output, lit); err != nil {
				return fmt.Errorf("value %q is not assignable to option %q", lit, optName)
			}

		}
	}

	if len(arguments) <= 0 {
		return fmt.Errorf("too few arguments")
	}
	if err := parseValue(&input.Arg_DataSource, arguments[0]); err != nil {
		return fmt.Errorf("value is not assignable to argument at [%d]", 0)
	}

	if len(arguments) <= 1-1 {
		return fmt.Errorf("too few arguments")
	}
	if err := parseValue(&input.Arg_TargetTables, arguments[1:]...); err != nil {
		return fmt.Errorf("values [%s] are not assignable to arguments at [%d:]", strings.Join(arguments[1:], " "), 1)
	}

	return nil
}

func NewCLI() CLI {
	return CLI{}
}

func Run(cli CLI, args []string) error {
	subcommandPath, restArgs := resolveSubcommand(args)
	switch strings.Join(subcommandPath, " ") {

	case "":
		funcMethod := cli.FUNC
		if funcMethod == nil {
			return fmt.Errorf("%q is unsupported: cli.FUNC not assigned", "")
		}
		var input CLI_Input
		err := resolve_CLI_Input(&input, restArgs)
		return funcMethod(subcommandPath, input, err)

	}
	return nil
}

func resolveSubcommand(args []string) (subcommandPath []string, restArgs []string) {
	if len(args) == 0 {
		panic("command line arguments are too few")
	}
	subcommandSet := map[string]bool{
		"": true,
	}

	for _, arg := range args[1:] {
		if arg == "--" {
			break
		}
		pathLiteral := strings.Join(append(append([]string{}, subcommandPath...), arg), " ")
		if !subcommandSet[pathLiteral] {
			break
		}
		subcommandPath = append(subcommandPath, arg)
	}

	return subcommandPath, args[1+len(subcommandPath):]
}

func parseValue(dstPtr any, strValue ...string) error {
	switch dstPtr := dstPtr.(type) {
	case *[]bool:
		val := make([]bool, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []bool: %w", str, err)
			}
		}
		*dstPtr = val
	case *[]float64:
		val := make([]float64, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []float64: %w", str, err)
			}
		}
		*dstPtr = val
	case *[]int64:
		val := make([]int64, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []int64: %w", str, err)
			}
		}
		*dstPtr = val
	case *[]string:
		val := make([]string, len(strValue))
		for idx, str := range strValue {
			if err := parseValue(&val[idx], str); err != nil {
				return fmt.Errorf("fail to parse %#v as []string: %w", str, err)
			}
		}
		*dstPtr = val
	case *bool:
		val, err := strconv.ParseBool(strValue[0])
		if err != nil {
			return fmt.Errorf("fail to parse %q as bool: %w", strValue[0], err)
		}
		*dstPtr = val
	case *float64:
		val, err := strconv.ParseFloat(strValue[0], 64)
		if err != nil {
			return fmt.Errorf("fail to parse %q as float64: %w", strValue[0], err)
		}
		*dstPtr = val
	case *int64:
		val, err := strconv.ParseInt(strValue[0], 0, 64)
		if err != nil {
			return fmt.Errorf("fail to parse %q as int64: %w", strValue[0], err)
		}
		*dstPtr = val
	case *string:
		*dstPtr = strValue[0]
	}

	return nil
}

func consumeVariables(...any) {}
